import { type NextPage } from "next";
import Head from "next/head";
import { SignInButton, SignOutButton } from "@clerk/nextjs";
import { useUser } from "@clerk/nextjs";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const user = useUser();

  const {data} = api.posts.getAll.useQuery()
  
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div>
          {
            user.isSignedIn ? (
              <SignOutButton>
                <button className="px-3 py-2 font-semibold rounded-full border-2 border-white text-white transition-colors hover:bg-white hover:text-black">Sign Out</button>
              </SignOutButton>
            ) : (
              <SignInButton>
                <button className="px-3 py-2 font-semibold rounded-full border-2 border-white text-white transition-colors hover:bg-white hover:text-black">Sign In</button>
              </SignInButton>
            )
          }
        </div>
        <div>
          {data?.map((post) => (<div key={post.id}>{post.content}</div>))}
        </div>
        
      </main>
    </>
  );
};

export default Home;
